### ISSUE TITLE
Add GUID to every fact record (fix TestDeepOps.test_id_select)

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/jx-sqlite#22]
Each fact record has a `UID = "__id__"`  used for joining nested records.  All fact records should also have a `GUID = "__guid__"` which is some long hex number to be used for inter-shard uniqueness.

The actual value of the GUID is hex to pass the test, but it should be easy to change.

**Comment by rohit-rk** [comment]
Is the GUID required for fact table only or for all the tables?

**Comment by klahnakoski** [comment]
Just the fact table requires a GUID

**Comment by klahnakoski** [comment]
resolved with https://github.com/mozilla/jx-sqlite/pull/33
