### ISSUE TITLE
Escaping dots in query (test_dots_in_property_names)

### ISSUE THREAD

**Issue by rohit-rk** [mozilla/jx-sqlite#24]
should we escape dots in query's select clause. As while executing query there won't be any column named such. I suspect that because may be by coincidence the tests passes on removing it. Working on this test , and wanted to confirm this first?

**Comment by klahnakoski** [comment]
This is a good question.  The columns are dot-delimited paths, which is good for anyone that may want to write standard sql against the tables that jx-sqlite manages; actually, I hope that remains a feature so other databases (which much more powerful query semantics) can be used without pain.  

Allowing dot-delimited names denies property names with dots in them.  We may want "a.html" as a column name referring to `{"a.html": 1}`, not referring to `{"a":{"html": 1}}`.  We could escape the literal dots, just like we do in other parts of the program with `\\`, which is simple solution, but a bit mindbending for a sql query writer. 

As long as the solution is contained (all table column names are shunted through the same encoder/decoder) I can be flexible with what you decide.

**Comment by klahnakoski** [comment]
Column names are put through `quote_column()` already.  We can make a new `quote_column()`, ?maybe in the snowflake? that can perform this name transformation then call sqlite's `quote_column()`.

**Comment by rohit-rk** [comment]
This is completed in [https://github.com/mozilla/jx-sqlite/pull/35](https://github.com/mozilla/jx-sqlite/pull/35)
