### ISSUE TITLE
test_edge_2 not working

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/jx-sqlite#7]
Specifically, the `test_count_rows`

**Comment by klahnakoski** [comment]
Let's go over the query that is generated.  It currently generates too many rows, so it results in index exception

    SELECT *

There are two major parts to this query, which will be sorting (at the end)

    FROM (
        SELECT 
            e0.d0c0 AS d0c0,
            e1.d1c0 AS d1c0,
            COUNT(__exists__) AS count
        FROM (

This is the fact table, we add an __exists__ to help us distinguish between a missing row and a row with null column value.  This happens during joins.  We also add any filter at this point.

          SELECT 1 __exists__, *
          FROM testing __a__
          WHERE 1
          ) __a__

We left join to ensure all records from the fact table are included, even if they match none of domains in the dimensions.

      LEFT JOIN (

This is the first dimension. It would be nice to have it as a table, but we build it explicitly.

          SELECT 0 AS rownum, 'x' AS d0c0
          UNION ALL          
          SELECT 1 AS rownum, 'y' AS d0c0
          UNION ALL
          SELECT 2 AS rownum, 'z' AS d0c0
          UNION ALL
          SELECT 3 AS rownum, NULL AS d0c0
          ) e0 

Next is the join condition: We *should* be matching the domain values to the `edge.value` in the query.  We are not doing this, so I suspect my strategy of copying a similar if block wrong.  I expecting something like `ON e0.d0c0 = "a.$string"`

      ON e0.d0c0 = CASE 
              WHEN (("a.$string") = ('x'))
                  THEN 0
              WHEN (("a.$string") = ('y'))
                  THEN 1
              WHEN (("a.$string") = ('z'))
                  THEN 2
              ELSE 3
              END

Since this query is 2-dimensional, we also left join the second dimension.  This will include all rows from the fact table, and include all rows from the first dimension. 

      LEFT JOIN (
          SELECT d1c0
          FROM (

We build a query to understand what is in the `b` column, we group by `b` to find some unique values, we sort by the count so we get the most common values, and we limit to 10 (any query that does not have a limit will default to a limit of 10).

              SELECT "b.$string" AS d1c0
              FROM testing __a__
              GROUP BY "b.$string"
              ORDER BY COUNT(1) DESC LIMIT 10
              )

And, of course, we join on the value.  We want to match to more than just the value: We want to catch the case when no record in the fact table matches (`"b.$string" IS NULL`) and include it in the case when `b` has nulls (`e1.d1c0 IS NULL`).  Notice we have no constraint on the first dimension (`e0`), which means we are including all fact records, and all first dimension records that matched a fact record.

         ) e1 ON e1.d1c0 = "b.$string"
          OR (
              e1.d1c0 IS NULL
              AND "b.$string" IS NULL
              )
      GROUP BY
 
we then group by the domains of the dimensions to get all combinations, and aggregate

          e0.d0c0,
          e1.d1c0

Done the main logic, but we missed a lot of records!!
      
      UNION ALL
      
The following is the code to catch all the residue domain values.  The `LEFT JOIN` is great for including everything in the fact table, but records from the domain tables are not included if there are no matches.  We must find the not-matching values from the two dimensions.  We could leave this out and let the python program figure out this residue, but I am assuming Sqlite will do it much faster than python can.

      SELECT 
          e0.d0c0 AS d0c0,
          e1.d1c0 AS d1c0,
          COUNT(__exists__) AS count
      FROM (

Here is the the first dimension, like before

          SELECT 0 AS rownum, 'x' AS d0c0
          UNION ALL
          SELECT 1 AS rownum, 'y' AS d0c0
          UNION ALL
          SELECT 2 AS rownum, 'z' AS d0c0
          UNION ALL
          SELECT 3 AS rownum, NULL AS d0c0
      ) e0
      LEFT JOIN (

The seconds dimension, like before

          SELECT d1c0
          FROM (
              SELECT "b.$string" AS d1c0
              FROM testing __a__
              GROUP BY "b.$string"
              ORDER BY COUNT(1) DESC LIMIT 10
              )

We join `ON 1=1` so we get all dimension combinations

          ) e1 ON 1 = 1
      LEFT JOIN (

We put the fact table as rightmost; We will ensure we get all rows from the two dimension tables 

          SELECT 1 __exists__,
              *
          FROM testing __a__
          WHERE 1
          ) __a__ ON (

We join so that each record from the fact table must match the dimensions.  Since we are including all dimensions, we will also get the rows that have no match in the fact table.

              e0.d0c0 = CASE 
                  WHEN (("a.$string") = ('x'))
                      THEN 0
                  WHEN (("a.$string") = ('y'))
                      THEN 1
                  WHEN (("a.$string") = ('z'))
                      THEN 2
                  ELSE 3
                  END
              )
          AND (
              e1.d1c0 = "b.$string"
              OR (
                  e1.d1c0 IS NULL
                  AND "b.$string" IS NULL
                  )
              )

The join ensures we have all dimensions in the result. We want to exclude any coordinates that have a fact record:

      WHERE (__exists__ IS NULL)

      GROUP BY 
          e0.d0c0,
          e1.d1c0
      )

These two parts are now properly sorted: `ORDER BY d0c0 IS NULL` ensures the null values are last.

    ORDER BY 
        d0c0 IS NULL,
        d0c0,
        d1c0 IS NULL,
        d1c0

**Comment by rohit-rk** [comment]
Yes, the created if block was also making the test cases of single dimensions(with partition) fail.
We do needed to match `ON e0.d0c0 = "a.$string"` and also on nulls.
       
              ON (e0.d0c0 = "a.$string" 

                   OR (e0.d0c0 IS NULL AND "a.$string" IS NULL)) 

             AND (e1.d1c0 = "b.$string"

                    OR (e1.d1c0 IS NULL AND "b.$string" IS NULL))

**Comment by rohit-rk** [comment]
I believe this is done.
