### ISSUE TITLE
ModuleNotFoundError: No module named 'jx_base'

### ISSUE THREAD

**Issue by setop** [mozilla/jx-sqlite#86]
When doing `pip install jx-sqlite` successfully.

And then `python -c 'from jx_sqlite.container import Container'`

I get `ModuleNotFoundError: No module named 'jx_base'`

In doubt, I tried `pip install jx-base` but got `ERROR: No matching distribution found for jx-base`.

**Comment by klahnakoski** [comment]
I have tried a few things to get this to properly package.  They problem is it was meant to be included in larger projects that have their own `requirements.txt`.  I am looking into the last project that deployed this.

**Comment by klahnakoski** [comment]
I fixed the CI pipeline, and forced this module to include its own version of all the `vendor` packages (which are quite old).  This deployed version is quite limited: Please see the number of skipped tests.

I have been working on another (low priority) branch that can use the newest versions of those packages, and pass more of the tests.

**Comment by klahnakoski** [comment]
@setop Please close this issue.  I do not have permission to close issue on this repo.

**Comment by setop** [comment]
I made a quick test today

```
docker run -it --rm python:alpine sh
pip install jx-sqlite
python -c 'from jx_sqlite.container import Container'
```
Then run the [code example](https://github.com/mozilla/jx-sqlite#code-example)

No more errors.
